### ISSUE TITLE
Android9.0 AlertDialog不居中显示问题

### ISSUE THREAD

**Issue by trycatchx** [yidun/quickpass-android-demo#10]
![image](https://user-images.githubusercontent.com/6050250/160114564-635f8be3-e7ca-43ea-a26a-f9e798986d35.png)
以上代码在demo 中不居中，建议解决：

参考：
https://blog.csdn.net/qq_38356174/article/details/87856639

**Comment by liulingfeng** [comment]
ok，这边看看先
