### ISSUE TITLE
点击一键登录的时候 没法加载loading弹窗

### ISSUE THREAD

**Issue by fengkai0516** [yidun/quickpass-android-demo#11]

**Comment by liulingfeng** [comment]
点击一键登录只是参数回传，没有耗时

**Comment by fengkai0516** [comment]
可以加载loding弹窗，解决了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 刘小帅 ***@***.***&gt;
发送时间: 2022年6月8日 15:24
收件人: yidun/quickpass-android-demo ***@***.***&gt;
抄送: fengkai0516 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yidun/quickpass-android-demo] 点击一键登录的时候 没法加载loading弹窗 (Issue #11)





 
Closed #11 as completed.

**Comment by fengkai0516** [comment]
有耗时，获取电话号码需要时间





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 刘小帅 ***@***.***&gt;
发送时间: 2022年6月8日 15:23
收件人: yidun/quickpass-android-demo ***@***.***&gt;
抄送: fengkai0516 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yidun/quickpass-android-demo] 点击一键登录的时候 没法加载loading弹窗 (Issue #11)





 
点击一键登录只是参数回传，没有耗时
