### ISSUE TITLE
3.2.0版本出现类名重复的问题

### ISSUE THREAD

**Issue by lageev** [yidun/quickpass-android-demo#12]
Duplicate class a.a.a.a.a.a found in modules jetified-opensdk-common-0.1.6.2-runtime (com.bytedance.ies.ugc.aweme:opensdk-common:0.1.6.2) and jetified-quicklogin-3.2.0-runtime (io.github.yidun:quicklogin:3.2.0)

看了下，和抖音某SDK混淆后的类名重复了，只是单纯的类名重复。

可以换一个更独特的字典吗？不知道是不是成本更低的解决方案

**Comment by lageev** [comment]
![WechatIMG422.png](https://s2.loli.net/2022/06/01/ZdUbTsmyp75wn8q.png)
![WechatIMG423.png](https://s2.loli.net/2022/06/01/1b7aU2mkedqnul9.png)

**Comment by lageev** [comment]
321版本，问题已解决

**Comment by liulingfeng** [comment]
混淆问题，降到3.1.9版本或者升级到3.2.2版本，3.2.2版本混淆规则已经改回来
