### ISSUE TITLE
求适配 AndroidX

### ISSUE THREAD

**Issue by lageev** [yidun/quickpass-android-demo#6]

**Comment by liulingfeng** [comment]
Android X目前您那边是什么问题

**Comment by lageev** [comment]
> Android X目前您那边是什么问题

在一键登录页的Activity上启动一些对话框（dialogFrament）。由于需要传入Activity作为参数，和自有项目的AndroidX 相关的内容不兼容，没办法完美使用

**Comment by liulingfeng** [comment]
收到，下周会上

**Comment by liulingfeng** [comment]
Android X已经支持，请使用远程依赖
