### ISSUE TITLE
crash 解决一下

### ISSUE THREAD

**Issue by trycatchx** [yidun/quickpass-android-demo#7]
```
* 1._Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.netease.nis.quicklogin.helper.UnifyUiConfig.getActivityExitAnimation()' on a null object reference_
 * 2._at com.netease.nis.quicklogin.ui.YDQuickLoginActivity.finish(SourceFile:2)_
 * 3._at com.netease.nis.quicklogin.ui.YDQuickLoginActivity$a.onClick(SourceFile:3)_
 * 4._at android.view.View.performClick(View.java:6331)_
```

**Comment by trycatchx** [comment]
```
1.Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
2.at com.netease.nis.quicklogin.utils.LoginUiHelper.Y(SourceFile:25)
3.at com.netease.nis.quicklogin.utils.LoginUiHelper.G(SourceFile:1)
4.at com.netease.nis.quicklogin.utils.LoginUiHelper$e.onActivityResumed(SourceFile:15)
5.at android.app.Application.dispatchActivityResumed(Application.java:229)
6.at android.app.Activity.onResume(Activity.java:1281)
7.at com.cmic.sso.wy.activity.LoginAuthActivity.onResume(SourceFile:1)
8.at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1276)
9.at android.app.Activity.performResume(Activity.java:6963)
10.at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3469)
11.at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3532)
12.at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1570)
13.at android.os.Handler.dispatchMessage(Handler.java:102)
14.at android.os.Looper.loop(Looper.java:154)
15.at android.app.ActivityThread.main(ActivityThread.java:6211)
16.at java.lang.reflect.Method.invoke(Native Method)
17.at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
18.at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:793)
```

**Comment by liulingfeng** [comment]
好的，感谢反馈

**Comment by liulingfeng** [comment]
> ```
> * 1._Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.netease.nis.quicklogin.helper.UnifyUiConfig.getActivityExitAnimation()' on a null object reference_
>  * 2._at com.netease.nis.quicklogin.ui.YDQuickLoginActivity.finish(SourceFile:2)_
>  * 3._at com.netease.nis.quicklogin.ui.YDQuickLoginActivity$a.onClick(SourceFile:3)_
>  * 4._at android.view.View.performClick(View.java:6331)_
> ```

新版本已解决 3.0.6.7

**Comment by trycatchx** [comment]
> ```
> 1.Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
> 2.at com.netease.nis.quicklogin.utils.LoginUiHelper.Y(SourceFile:25)
> 3.at com.netease.nis.quicklogin.utils.LoginUiHelper.G(SourceFile:1)
> 4.at com.netease.nis.quicklogin.utils.LoginUiHelper$e.onActivityResumed(SourceFile:15)
> 5.at android.app.Application.dispatchActivityResumed(Application.java:229)
> 6.at android.app.Activity.onResume(Activity.java:1281)
> 7.at com.cmic.sso.wy.activity.LoginAuthActivity.onResume(SourceFile:1)
> 8.at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1276)
> 9.at android.app.Activity.performResume(Activity.java:6963)
> 10.at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3469)
> 11.at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3532)
> 12.at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1570)
> 13.at android.os.Handler.dispatchMessage(Handler.java:102)
> 14.at android.os.Looper.loop(Looper.java:154)
> 15.at android.app.ActivityThread.main(ActivityThread.java:6211)
> 16.at java.lang.reflect.Method.invoke(Native Method)
> 17.at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
> 18.at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:793)
> ```

这个crash 解决了吗？

**Comment by liulingfeng** [comment]
> > ```
> > 1.Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
> > 2.at com.netease.nis.quicklogin.utils.LoginUiHelper.Y(SourceFile:25)
> > 3.at com.netease.nis.quicklogin.utils.LoginUiHelper.G(SourceFile:1)
> > 4.at com.netease.nis.quicklogin.utils.LoginUiHelper$e.onActivityResumed(SourceFile:15)
> > 5.at android.app.Application.dispatchActivityResumed(Application.java:229)
> > 6.at android.app.Activity.onResume(Activity.java:1281)
> > 7.at com.cmic.sso.wy.activity.LoginAuthActivity.onResume(SourceFile:1)
> > 8.at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1276)
> > 9.at android.app.Activity.performResume(Activity.java:6963)
> > 10.at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3469)
> > 11.at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3532)
> > 12.at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1570)
> > 13.at android.os.Handler.dispatchMessage(Handler.java:102)
> > 14.at android.os.Looper.loop(Looper.java:154)
> > 15.at android.app.ActivityThread.main(ActivityThread.java:6211)
> > 16.at java.lang.reflect.Method.invoke(Native Method)
> > 17.at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
> > 18.at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:793)
> > ```
> 
> 这个crash 解决了吗？

解决了
